### ISSUE TITLE
Cannot upload to root of S3 bucket

### ISSUE THREAD

**Issue by zezke** [jenkinsci/pipeline-aws-plugin#41]
I am using a S3 bucket to host a small website (fronted by CloudFront). I have an Angular CLI project that needs to be uploaded to the S3 bucket's root, but I cannot seem to get it working.

```s3Upload(bucket: 'com.zezke.portal', includePathPattern:'**/*', workingDir:'dist')```

results in `java.lang.IllegalArgumentException: Path must not be null or empty when uploading file`. Adding a path parameter and setting it to '.' or  '/' does not work either.

```s3Upload(bucket: 'com.zezke.portal', path: '.', includePathPattern:'**/*', workingDir:'dist')```

This creates a folder in the S3 bucket, not quite the goal I want either.

Any idea how to upload a bunch of files to the root of an S3 bucket?

**Comment by SamVerschueren** [comment]
Thanks for fixing this @hoegertn 🎉 ! Any chance this fix can be released?

**Comment by hoegertn** [comment]
I will test all the changes I did and will try to release today or tomorrow.

**Comment by zezke** [comment]
@hoegertn How did the tests go? Anything I can help with? Any update on a potential release?

**Comment by hoegertn** [comment]
should be fixed with 1.22

**Comment by robertcepa** [comment]
This still doesn't work.
`s3Upload(bucket: "${bucketName}", includePathPattern:'**/*', workingDir:'build')`

Jenkins says Upload complete, but when I check my S3 bucket it's empty.
Is there any other way to copy the contents of my build folder to a S3 bucket root?

**Comment by judezhu** [comment]
@robertcepa  this works for me
